### ISSUE TITLE
Why api methods don't work

### ISSUE THREAD

**Issue by Alexander-Pereyaslovets** [openprocurement/openprocurement.tender.openua#16]
Hello. When I'm trying to call api method http://api-sandbox.openprocurement.org/api/2.3/tenders
via Postman (is a Chrome App) I'm geting next error "Could not get any response". Can you tell me why this method didn't work?

**Comment by shady77** [comment]
Try use https://api-sandbox.openprocurement.org/api/2.3/tenders
